### ISSUE TITLE
Combining whitelist_routes and only_allow_logged_in_rest_access

### ISSUE THREAD

**Issue by TangRufus** [dmchale/disable-json-api#10]
Simplifying`Disable_REST_API` by combine `whitelist_routes` and `only_allow_logged_in_rest_access`. 

Hooking `rest_authentication_errors` twice makes it more complicated than necessary.

**Comment by dmchale** [comment]
Done. Hooking at priority 20, to give some flexibility before and after (but mostly make sure we hook AFTER most other things will at default priority) : https://github.com/dmchale/disable-json-api/commit/6147458ace09fe9143500ebd653ad8b376bd65a6
