### ISSUE TITLE
Use placeholders for i18n strings

### ISSUE THREAD

**Issue by TangRufus** [dmchale/disable-json-api#15]
Use placeholders for i18n strings, such as

https://github.com/dmchale/disable-json-api/blob/a4f8cc57ca0558a0d5f9da8862e14e677076712a/admin.php#L69

Reason: Not language put 'rest_url()' at the end of the sentence. 

See: https://codex.wordpress.org/I18n_for_WordPress_Developers#Placeholders

**Comment by dmchale** [comment]
All set, confirmed in Loco Translate things seem to look good : https://github.com/dmchale/disable-json-api/commit/dea0db92c5194f26da74bef5ab2b28c290ea43b4
