### ISSUE TITLE
If pretty permalinks is enabled and wp-admin lives in a directory, settings page can't get endpoints

### ISSUE THREAD

**Issue by TangRufus** [dmchale/disable-json-api#2]
Example:

![disable_rest_api_settings_ _wordpress_site_ _wordpress](https://user-images.githubusercontent.com/2259834/29743961-b0b8572a-8a60-11e7-9104-25628cdb03c0.png)

When pretty permalinks is disabled, it works.

**Comment by dmchale** [comment]
All set! https://github.com/dmchale/disable-json-api/commit/f907172e83021f622b3007ef363bc5fa6c610cdc 

This does open my eyes to the fact that I have additional testing to do for multisite, too. These functions won't work properly on multisite installs but I thought I'd patch this for now and circle back to those.

**Comment by TangRufus** [comment]
Try:

```javascript
var restPath = '<?php echo rest_url(); ?>';
```

See:
- https://developer.wordpress.org/reference/functions/rest_url/
- https://developer.wordpress.org/reference/functions/get_rest_url/

**Comment by TangRufus** [comment]
Going further:

1. Get `routes` by PHP:
```php
$wp_rest_server = rest_get_server();
$ routes = $wp_rest_server->get_routes();
```
2. Pass `routes` to JS via [`wp_localize_script`](https://developer.wordpress.org/reference/functions/wp_localize_script/)

This can save some jQuery ajax code.

**Comment by dmchale** [comment]
Converted admin page to php-based rather than JS-based: https://github.com/dmchale/disable-json-api/commit/6af19e4377efdc639ad53ee08dbdc3df15753f95
