### ISSUE TITLE
Dead code: `Disable_REST_API::load_plugin_textdomain`

### ISSUE THREAD

**Issue by TangRufus** [dmchale/disable-json-api#20]
`Disable_REST_API::load_plugin_textdomain` condition never true because that class never run on WP 4.6 or below.

https://github.com/dmchale/disable-json-api/blob/182453636ccfba2057a42a896d8d9d457c8d17ad/disable-json-api.php#L26

https://github.com/dmchale/disable-json-api/blob/182453636ccfba2057a42a896d8d9d457c8d17ad/classes/disable-rest-api.php#L44

**Comment by dmchale** [comment]
Hah! I knew something was bothering me about that code, but I couldn't pin down what/why. That was it  Removed: https://github.com/dmchale/disable-json-api/commit/30ca58248d05752fd3a24cbbccc76d9613c345e4
