### ISSUE TITLE
Version number needs update

### ISSUE THREAD

**Issue by TangRufus** [dmchale/disable-json-api#21]
Although everything still works without this, updating version number in `disable-json-api.php` gives better user experience:
- wp.org shows this version number on https://wordpress.org/plugins/disable-json-api/ 
- admin dashboard shows this version number on plugin page

![disable_rest_api_ _wordpress_plugins](https://user-images.githubusercontent.com/2259834/30356980-ca68518a-9801-11e7-810a-3bed3c3701bd.png)

https://github.com/dmchale/disable-json-api/blob/897914e0ea3cbca85f89b9c983b0e95efbead10e/disable-json-api.php#L6

**Comment by dmchale** [comment]
Fixed, thanks. For some reason I thought the repo read that data from the readme file so I didn't bother updating both. I saw the plugin page was still showing 1.4, but thought maybe the system was lagging in updating itself. 

I pushed to the 1.4.1 tag release, and to trunk. Commit here at githib : https://github.com/dmchale/disable-json-api/commit/12140d62746e5d90838dcf0be87f01842acec80a
