### ISSUE TITLE
Whitelist does not work for subsite when plugin is network enabled

### ISSUE THREAD

**Issue by CHadetz** [dmchale/disable-json-api#27]
My custom endpoint (whitelisted on subsite) returns 401 when the plugin is network activated. If I enable the plugin on the subsite only the whitelist works as expected.

Network activated -> domain.com/subsite/endpoint -> 401
Single site activated -> domain.com/subsite/endpoint -> 200

**Comment by dmchale** [comment]
Hi @CHadetz thanks for the report! Do you have a link to a public environment where I could take a look at this happening? Any additional information you're willing to provide would be much appreciated. Thanks!

**Comment by CHadetz** [comment]
Sorry, no public env for this. I tried setting up a sandbox multisite but failed.
However I fiddled around some more and found out that when the plugin is network activated, any changes to whitelist on a single site go unnoticed. So when I remove the endpoint from whitelist, it keeps open.

Single site activated -> domain.com/subsite/endpoint -> 200
-> network activate plugin
-> remove endpoint from whitelist on single site
Network activated -> domain.com/subsite/endpoint -> 200

**Comment by dmchale** [comment]
Hi @CHadetz  haha no worries, that happens to the best of us! Perhaps you were still logged in as a user when you were testing different settings from the admin? Reminder that the plugin will ONLY blacklist endpoints for non-authenticated users, but if you're logged in as any type of user at all then you'll default back to the route's default behavior. 

I'm going to close this Issue for now, but please feel free to update if you find anything amiss later that may be a bug we should investigate. Cheers!
