### ISSUE TITLE
 Using `filemtime` to cache bust editor assets is not reliable

### ISSUE THREAD

**Issue by TangRufus** [dmchale/disable-json-api#29]
https://github.com/dmchale/disable-json-api/blob/5e5bf4cc0cde163e2b0e6445c15a868c58f3e3af/classes/disable-rest-api.php#L192-L194

See: https://github.com/WordPress/gutenberg/issues/18227

**Comment by dmchale** [comment]
cheers @TangRufus ! Wasn't aware this was a frowned-upon pattern nowadays, using the plugin version makes sense though.

**Comment by TangRufus** [comment]
Looks good to me. 🎉
