### ISSUE TITLE
Better Internationalization

### ISSUE THREAD

**Issue by TangRufus** [dmchale/disable-json-api#4]
- Some strings are not internationalized
- `load_plugin_textdomain()` needed for WP 4.4 and 4.5

See: https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/

**Comment by dmchale** [comment]
Finding untranslated strings, making function updates (escaping html & attributes now): https://github.com/dmchale/disable-json-api/commit/12dddaf13d5deb85999822e9381ce71db40af697 

Adding `load_plugin_textdomain()` support: https://github.com/dmchale/disable-json-api/commit/87e139d7c08d4ac4f85292d281c990439552c339
