### ISSUE TITLE
wordpress version says 3 versions out of date...

### ISSUE THREAD

**Issue by 4evermaat** [dmchale/disable-json-api#46]
https://wordpress.org/plugins/disable-json-api/#description

Not sure if that was intentional or not.  It would be good to update it and show people that plugin will still work ok on later versions of wordpress.

Actually it was a user comment that lead me here (saying that the plugin should still be valid for later 6.xx versions)

**Comment by dmchale** [comment]
This has been taken care of with the last release of v1.8. Closing issue
