### ISSUE TITLE
Wordfence marks "Disable REST API" as abandoned

### ISSUE THREAD

**Issue by Detsieber** [dmchale/disable-json-api#47]
The full message from Wordfence is:

> 
> The Plugin "Disable REST API" appears to be abandoned (updated 29. July 2021, tested to WP 5.8.7).
> Type: Plugin Abandoned
> Issue Found 2. August 2023 17:13
> Medium
> [Ignore](https://civiservice.de/wp-admin/admin.php?page=WordfenceScan#)
> 
>     [Details](https://civiservice.de/wp-admin/admin.php?page=WordfenceScan#)
> 
>     Plugin Name: Disable REST API
>     Current Plugin Version: 1.7
>     Last Updated: 29. July 2021
>     Details: It was last updated 2 years 0 months ago and tested up to WordPress 5.8.7. Your site is still using this plugin, but it is not currently available on wordpress.org. Plugins can be removed from wordpress.org for various reasons. This can include benign issues like a plugin author discontinuing development or moving the plugin distribution to their own site, but some might also be due to security issues. In any case, future updates may or may not be available, so it is worth investigating the cause and deciding whether to temporarily or permanently replace or remove the plugin. [Get more information.](https://www.wordfence.com/help/?query=scan-result-plugin-abandoned&utm_source=plugin&utm_medium=pluginUI&utm_campaign=docsIcon)
> 

The plugins works fine, and we are using it one a large number of sites using WordPress 6.2.x
Probably, it would be enough to update "tested with WordPress 6.2.xxxx" and publish a new release.

Otherwise, users could be afraid this plugin were "really" abandoned...

PS: Thanks for your work!

**Comment by dmchale** [comment]
resolved with the release of v1.8. Closing issue
