### ISSUE TITLE
Add `Requires PHP: X.X.X` to readme.txt

### ISSUE THREAD

**Issue by TangRufus** [dmchale/disable-json-api#9]
Though i don't know what is the minimum requirement

See: https://meta.trac.wordpress.org/changeset/5841

**Comment by dmchale** [comment]
Updated readme to target 5.3+: https://github.com/dmchale/disable-json-api/commit/8846d07f3b830025b4677687949fbecd46f8c887 

Patched admin.php to prevent fatal error "Can't use function return value in write context" on older versions of PHP. Plugin now seems to work fine with no warnings/errors down to PHP 5.3: https://github.com/dmchale/disable-json-api/commit/6ee0f0e7192f4210e8827f49f53d1596ae289775
